### ISSUE TITLE
All future work according to test since 8/5 (gathered from existed issues)

### ISSUE THREAD

**Issue by freindst** [ArgoBus/Argo-Project-V0#99]
These problems are not listed according to priority.
 - [x] 1. We need to have a complete plan about creating trip page. I think this page is used to make organizer tell everything we might need in order to prepare a trip. #76 
![image](https://cloud.githubusercontent.com/assets/13219475/9141406/04b30382-3cfe-11e5-827f-554a89637e9d.png)

 - [x] 2. radio button visual effect #78 
![image](https://cloud.githubusercontent.com/assets/13219475/9141451/664e2e82-3cfe-11e5-91ee-93a7c1996ca8.png)

 - [x] 3. Time/date picker #82 
It will be better if we have it. As not all browser support html5
![image](https://cloud.githubusercontent.com/assets/13219475/9141529/04cda07e-3cff-11e5-98a5-2af3c80e7b7f.png)

 - [x] 4. Excuse me for re-mentioning it. Create template page background. #87 

 - [x] 5. Pledge confirmation process #89. Right now, it is a list of username(email) and user's full name. I will make a change based on our next discussion. Remove email is simple. What else I need to do is add an email notification after user successfully pledged a trip #96. In addition, put social media sharing button there. I guess we can add sharing button in the footer, so user can always click share button if he/she want.
![image](https://cloud.githubusercontent.com/assets/13219475/9141659/03039cb6-3d00-11e5-847c-38c7b0d58cc9.png)

 - [ ] 6. to me, #90 and #91 is not important at all right now.

 - [ ] 7. Home page visual effect. #93 

 - [x] 8. #94 displays. Actually some user feedback in #98 also mentioned this confusing part. In fact, simply change "duncan" to user.last_name in .jade file can solve the problem.

 - [x] 9. Security. #97 and #98. I have some ideas, maybe not enough or accurate.
First of all, all of us need to study what an online payment website(business) should do in order to prevent legal problems.
Second, Build secured http link, https://argobus.com instead of http://argobus.com
Third, find solutions to prevent security bugs, such as SQL injection ( I am not sure sequelize have this problem)
Fourth. Add encryption during sensitive data transfer.

#98 has too many topics. I will put in different replies below.

**Comment by freindst** [comment]
- [ ] 10. privacy related to email address, payment info
![image](https://cloud.githubusercontent.com/assets/13219475/9142162/8890b1e0-3d03-11e5-8cc2-d15671824e0b.png)

**Comment by freindst** [comment]
- [ ] 11. Reorganize all notification messages, to make them clear, direct and attractive.
![image](https://cloud.githubusercontent.com/assets/13219475/9142157/7d313806-3d03-11e5-9f78-2a99a341976d.png)

**Comment by freindst** [comment]
- [ ] 12. Trip list
User Suggestion
![image](https://cloud.githubusercontent.com/assets/13219475/9142178/acb36e64-3d03-11e5-98d5-0e568a3b20f3.png)
Current
![image](https://cloud.githubusercontent.com/assets/13219475/9142205/cee3dc26-3d03-11e5-932d-538720ef4f78.png)

**Comment by freindst** [comment]
- [ ] 13. Displays
User Suggestion
![image](https://cloud.githubusercontent.com/assets/13219475/9142232/f76525a6-3d03-11e5-81f6-234637444917.png)
First idea is similar to mine in #87.
Second is input formatting. We need to implement auto formatting and validation.

**Comment by freindst** [comment]
- [ ] 14. Text message notification support
![image](https://cloud.githubusercontent.com/assets/13219475/9142374/ef71a256-3d04-11e5-84f5-dfc787a7aef5.png)

**Comment by freindst** [comment]
- [ ] 15. More way to tell user how they can save money by inviting more people to the trip
![image](https://cloud.githubusercontent.com/assets/13219475/9142407/220d1dbc-3d05-11e5-9bb5-c7cfd33b30e4.png)
1. Some attractive way to tell user how price changes according to user, like odometer design, in trip list page and pledging confirmation page (or everywhere?)
2. Add trip template to all email notification to tell user.
3. Add a line "after another 10 people join the trip, you will get extra $10 off" to text notification or email
and so on

**Comment by markstm17** [comment]
There is a lot of awesome info, suggestions and things to work with here. What's your biggest piece of advice for handling this issue @duncangraham ??

**Comment by markstm17** [comment]
There is so much information on here right now, I don't think most of it is relevant or a major issues/tickets anymore.

I'm going to let you read over the issues and check boxes that Blade put together and I'll let you see if anything from your perspective is relevant anymore with where we are @duncangraham 

Message back if there are any and if you have any questions, and close if you don't

**Comment by duncangraham** [comment]
Most of the points here have been completed, but we do need to continue pushing on 14/15. Those two points have tickets elsewhere though so I'm closing this one.
